rgw: fix build issue
rgw/rgw_user.cc: In member function 'virtual int RGWUserMetadataHandler::put(RGWRados*, std::string&, RGWObjVersionTracker&, time_t, JSONObj*, RGWMetadataHandler::sync_type_t)':
rgw/rgw_user.cc:2390:23: error: 'uci' was not declared in this scope
       decode_json_obj(uci, obj);
                       ^

this bug is introduced by commit: 98e9a18e

Signed-off-by: isyippee <yippee_liu@163.com>